# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  releasenoteshub_job:
      runs-on: ubuntu-latest
      name: Github action to Pull Release Notes from GitHub for Version
      steps:
      - name: Checkout
        uses: actions/checkout@v2    
      - name: ReleaseNotesHub Pull step      
        uses: ./ # Uses an action in the root directory
        id: GitHubPullAction
        with:
          rnh-apikey: 'API-8d0fd1d2-8e3d-446d-a836-97016f3dba7e'
          rnh-projectid: '0a02d38d-0d8a-432d-b80f-79b1d3fe1bde'  
          rnh-release-version: '12.11.5.1'
          rnh-release-publish: 'true'     
